tailscale/golink

- golink.go
previously, the 200 links included in the "popular links" list were non-deterministic (though those 200 were sorted). Now, always shows the top 200.
> golink: truncate clicks slice after sorting

- db.go
- golink.go
go/.export doesn't include click data anymore since we switched over to sqlite.  Remove that code as well as the Link.Clicks field.  Remove old /_/export redirect, since we've long since moved off of using it.
> all: remove some dead code

- README.md
flyctl has updated: `Command "create" is deprecated, replaced by 'apps create'`
> Update README.md to fix a change in flyctl

- golink.go
- golink_test.go
Adds strings.TrimSuffix to the function map, enabling it to be used in URL definitions.
This accompanies the discussion in #9 and is motivated by the browser misfeature of my Safari instance, which fails to recognize a local domain URL as a URL unless it has a trailing slash. The intended use of this function is to trim that trailing slash.
(There is most certainly some more elegant way to do this, but as a start this is the one-line fix suggested by @willnorris that lets me make forward progress.)
> add TrimSuffix to the function map

- golink.go
Add a `--hostname` flag to allow changing the hostname from "go".
May be necessary if your workplace already has "go" links.
> cmd/golink: add `--hostname` flag

- Dockerfile
- README.md
The Dockerfile should use a directory writeable by nonroot for sqllite.
Fixes #6 
Signed-off-by: Adrian Mouat <adrian@chainguard.dev>
> Use a directory writable by nonroot.

- golink.go
- static/opensearch.xml
- tmpl/base.html
- tmpl/opensearch.xml
Proof of concept of adding support for browser based keyword search. This will require additional templating to fill in the xml with the actual `hostname`
This will help with safari (and chrome), as it will add the hostname as a keyword search.
Easy to test out using: `go run ./cmd/golink -dev-listen :8080`
In the below example you could `localhost test` and it would resolve to `localhost/test` which would then golink to the configured place.
docs: 
https://developer.mozilla.org/en-US/docs/Web/OpenSearch#autodiscovery_of_search_plugins
> add support for browser bar search keyword

- README.md
- golink.go
- golink_test.go
We technically don't even need the `-resolve-from-backup` flag.  Otherwise, callers would just need to specify:
```
golink -sqlitefile ":memory:" -snapshot /path/to/snapshot.json linkname
```
As implemented, it just sets those two flags and enforces that a link to be resolved is specified.  Maybe that's still worth keeping?
Fixes #15
> add support for resolving links locally

- .github/workflows/docker.yml
Build docker images for amd64, arm64, and arm/v7.  Also several other small improvements to docker workflow like documenting which actions we run on, setting concurrency settings, and reversing the logic for when we push new images live (specifically looking for a push event rather than a "not pull request" event, in case we add other events later).
> .github: cross-compile docker images

- db.go
- db_test.go
When loading stats from the database, map IDs back to their canonical short name, which is what we want to show in the frontend.  This is only called once on cold start, so performance of loading all links isn't a big concern.
Fixes #13
> db: use canonical link short name in stats

- golink.go
Currently, the special "tagged-devices" user (which exists for any tagged devices in the tailnet) can own go links.  This change permits tagged devices to continue to create go links, but skips over them for ownership checks, allowing any human user can take over ownership.
Fixes #37
> skip "tagged-devices" in userExists check

- Dockerfile
Most of the details are in https://github.com/chainguard-images/images/issues/182.  At the end of last year, Chainguard switched from alpine+musl to wolfi+glibc as their default for their go images.  These new images are only built for linux/amd64 and linux/arm64.  We'd build for linux/arm/v7 as well in order to support older raspberry pis, which is only available in the musl images.
Fixes #42
> Dockerfile: use musl variant for go build image

- Dockerfile
Use a build image built for the native architecture so that it doesn't run in emulation mode.
This also allows us to switch to Chainguard's wolfi/glibc build image. This limits our build architectures to just amd64 and arm64, but that is sufficient for our needs.
Recently our build times have been [up to 20 minutes](https://github.com/tailscale/golink/actions/runs/3877555256/jobs/6612746902); this brings them back down to about [3 minutes](https://github.com/tailscale/golink/actions/runs/3879584909/jobs/6616899415).
(cc @amouat as FYI)
Updates #42
Updates #43
> Dockerfile: cross compile images using native builder

- .github/workflows/nix.yml
- .gitignore
- flake.lock
- flake.nix
This commit adds a Flake.nix file allowing Nix users to consume this repo with `nix build`, `nix run` and adds a NixOS module to quickly spin up the service.
Signed-off-by: Kristoffer Dalby <kristoffer@dalby.cc>
> Add Flake file (Nix package, NixOS module)

- golink.go
- golink_test.go
- tmpl/help.html
Add "User" to the expansion environment for links.  The intent here it support personalized go links such as:
go/mycal => https://calendar.google.com/calendar/embed?src={{.User}}
That's not a terribly interesting example, but there are others I intend to use internally.
There's small risk of this being used to do things like track who clicks what links... 
go/secret => http://secret-link/?clicked-by={{.User}}
But using go links to do that is kinda boring... any service on your tailnet can already tell who the authenticated user, so this doesn't really reveal anything new.
> include current user resolving link in expandEnv

- golink.go
- golink_test.go
It's not uncommon to have multiple links pointing to the same destination, for example to handle different spellings of a word or because different people created them at different times.
A common best practice is to select one as the "primary" link and point the others to that link as "aliases".  This change updates resolveLink to follow those aliases so that the final destination is returned when using `golink -resolve-from-backup`.
> golink: allow -resolve-from-backup to resolve alias links

- golink.go
- golink_test.go
Also check error returned from tmpl.Execute. Refactor currentUser to make the logic a little simpler, and make it a package var for easier testing.
This doesn't make any behavioral changes (aside from checking the tmpl.Execute error).  Instead, it's focused on making the  next pass at #72 much simpler to review.
> add tests for serve methods

- go.mod
- go.sum
bump version again, back to the latest commit on main, rather than the latest released version. Otherwise, this causes issues in tailscale's corp repo (sadly).
> go.mod: bump tailscale.com version

- flake.lock
- flake.nix
This PR updates the nix hash to mirror go.mod, and it updates the nix dependencies used for building.
It addresses the build error in #72.
Signed-off-by: Kristoffer Dalby <kristoffer@tailscale.com>
> nix: update flake hash to mirror go.mod

- golink.go
- golink_test.go
This PR contains three separate commits that incrementally improve handling of query parameters in go links.  It's probably best to review the separately, in order.
Test cases pretty clearly show the kinds of requests this adds support for.
[edit] I removed support for appending the path remainder (in the default case with no go templates) and separately combining the query strings.  That was just too complicated, and was pretty contrived to begin with.  You can still achieve the same by using a go template in the long URL to append the path.
Fixes #77
> add support for query parameters in go links

- golink.go
- golink_test.go
First of all, thanks for golink!
**Description**
It should be possible to delete links owned by non-existing users (tagged-devices or deleted) in the same ways as it's possible to edit these links.
**Related PRs**
* https://github.com/tailscale/golink/pull/72
* https://github.com/tailscale/golink/pull/74
> Allow deletion of unowned links

- tmpl/detail.html
The detail page of a link only displays the form if the link is editable for the logged in user.
Therefore, it's not necessary to disable the input fields within the form if the link isn't editable.
> remove unused input field attribute disabled in details form

- Dockerfile
Chainguard is no longer allowing free users to use specific versions of images like go (instead, having to always use "latest"). So instead, we will create our own build image by installing the needed packages on top of the wolfi-base image.
This is one of the recommended approaches in their migration guide: https://www.chainguard.dev/unchained/a-guide-on-how-to-use-chainguard-images-for-public-catalog-tier-users
Fixes #82
> Dockerfile: stop using chainguard go image

- golink.go
- golink_test.go
Both http.ServeMux as well as the http.Redirect method pass the request URL through `cleanPath` which, among other things, collapses double slashes `//` to a single slash `/`. Most of the time this is fine, since most servers treat those as identical anyway. But some destination servers need the original path unmodified. Since we're just redirecting, we don't need to be concerned with the additional benefits of `cleanPath` such as eliminating `../` path components, since that is the responsibility of the destination server to clean if needed.
This change adds a separate root http.Handler for golink requests. It still uses http.ServeMux for internal endpoints, but serves golinks directly without passing the request through ServeMux. Additionally, this sets the redirect status and Location …
> golink: don't modify URL path when resolving link

- golink.go
In 46ed42f, I mistakenly only attached the serveHandler to the dev listener, but not tsnet.
Fixes #91
> golink: use new serveHandler with tsnet

- golink.go
I didn't think the order mattered (as long as none of the response body had been written), but I guess I was wrong. Currently, it's returning the 302 status, but no Location header. And tests, at least some of which should be passing through this full code path, are passing. I'll look into adding better testing later, but for now this fixes the immediate issue.
Updates #91
> golink: set HTTP status after Location header

- .github/workflows/docker.yml
- .github/workflows/tests.yml
The first commit runs the yaml files through prettier to use whatever common formatting it has.
The second commit updates the GitHub actions used for publishing the docker image.  The version of cosign we were using is apparently not published any longer(?) and was [causing errors](https://github.com/tailscale/golink/actions/runs/6872874346).  It also looks like the Fly issue with buildx [has been resolved](https://community.fly.io/t/10171/39), so stop pinning to buildx 0.9.1
Successful test run: https://github.com/willnorris/golink/actions/runs/6872887373
> Update github actions workflow for publishing docker image

- README.md
- golink.go
- golink_test.go
- tmpl/help.html
Updates tailscale/golink#9
Fixes tailscale/golink#29
On tailnets with TLS enabled serve HTTP traffic with a separate redirectHandler which sends requests to our HTTPS listener destination.
Add `-L` to documented examples of using `curl` to follow these redirects if present.
> golink: listen on HTTPS and redirect HTTP traffic

- golink.go
Fixes https://github.com/tailscale/golink/issues/102
Ensure that we have CertDomains for the HTTPS listener before asking
tsnet to create one.
> golink: check for CertDomains before enabling HTTPS

- flake.nix
Fix for https://github.com/NixOS/nixpkgs/pull/258680
network-online.target must now be explicitly depended on
> Fix for https://github.com/NixOS/nixpkgs/pull/258680

- flake.nix
- update-flake.sh
When including the flake into my nixos system and doing a rebuild I get the following error:
```
trace: warning: 'vendorSha256' is deprecated. Use 'vendorHash' instead
```
The `vendorHash` function is a drop in replacement, so with this PR the warning will be gone.
(The deprecation of `vendorSha256` can be verified by checking the [nixos 23.11 release notes](https://nixos.org/manual/nixos/stable/release-notes#sec-release-23.11) that say "The argument vendorSha256 of buildGoModule is deprecated. Use vendorHash instead. Refer to [PR #259999](https://github.com/NixOS/nixpkgs/pull/259999) for more details.")
> Replace deprecated Nix vendorSha256 call with vendorHash

- flake.nix
- go.mod
- go.sum
We have fixed the issue in the corp repo that required us to use pseudo-versions for the tailscale.com module here. So we can now switch to the latest stable version.
> go.mod: use latest stable build of tailscale

- golink.go
we've had support for enabling the web UI in tsnet apps from the beginning, but I don't think we've ever actually used it anywhere. some of the settings exposed through the web ui don't make a ton of sense for tsnet, and might not even work.  But we're working toward being able to enable the web ui on clients by default (with all of the existing restrictions and ACL enforcement in place), and golink seemed like a good playground to try it in a tsnet app.
> enable new web ui for managing node

- golink.go
- tmpl/home.html
If you visit a non-existent go link, we render the home page and pre- populate the "short" input with the name of the link, and autofocus the "long" input so that you can simply paste a long URL and submit.
It is common (at least at Tailscale) to create go links that correspond to the name of a device on the tailnet.  For example, go/who points to http://who/.  With this change, when you visit a non-existent go link, we check to see if a peer exists on the tailnet with that name, and if so we suggest that as the long URL.
Example:
> suggest long URL for new go links if peer exists

- README.md
Updates #18
Updates #22
Updates #86
Updates #120
> README: document permission model and grants

- flake.nix
golink is a tsnet service, and Tailscale's data plane is very good at monitoring for changes to network state and reacting to them. As such, it doesn't need to wait for network-online.target, it can start up concurrently with everything else and shorten the long pole of bootup.
Additionally, network-online.target is an antipattern in systemd that almost never means what people want it to mean. "Online" has no precise definition, and (I posit) almost never matches the ideal version of "online" that people have in their mind. It specifically does _not_ mean that the network functions, or that any particular flavor of connectivity exists. A machine behind a captive portal is "online" for the purposes of bootup, and so is a machine that got a DHCP lease but is having all its packets …
> flake.nix: don't wait for network-online.target to start golink

- golink.go
- golink_test.go
- tmpl/help.html
Add a "Match" template func, which uses regexp.MatchString to match a value against a regular expression pattern.
Internal discussion: https://tailscale.slack.com/archives/C03DHMXREA3/p1715099034944409
cc @garrett-ts
> add regexp.Match to template funcs

- .github/workflows/docker.yml
we've never tagged stable releases, but should really do so.  This change will cause our docker images to be tagged following typical semver fashion... the initial `v1.0.0` release will be tagged `v1`, `v1.0`, `v1.0.0`, and `latest`.
Updates #104
Tested in a fork at [willnorris/tmpgolink](https://github.com/willnorris/tmpgolink).  GitHub Action r[un at the v1.0.0 tag](https://github.com/willnorris/tmpgolink/actions/runs/8529904724), and the [resulting published image](https://github.com/willnorris/tmpgolink/pkgs/container/tmpgolink).
> use semantic version tagging for docker images

- golink.go
Two fixes, both of which would be sufficient on their own, but are both still worth doing:
- redirect `/.detail/` URLs to always use canonical link names. For example, for a `go/foo` link, a request to `/.detail/F-O-O` will redirect to `/.detail/foo`.
- use the canonical link short name for xsrf token generation and validation, rather than the user-provided short name.
Fixes #128
> fix xsrf issues on link update and delete

- golink.go
- tmpl/all.html
- tmpl/base.html
- tmpl/delete.html
- tmpl/detail.html
- tmpl/help.html
- tmpl/home.html
- tmpl/opensearch.xml
- tmpl/success.html
We would like our html templates to reflect the hostname override we are passing to golink, these changes pass the hostname to all HTML templates
> Pass hostname to all html templates

- Dockerfile
Chainguard removed arm/v7 support from their free images: https://www.chainguard.dev/unchained/changes-to-static-git-and-busybox-developer-images
Switch to the official `go` image for builds and distroless for packaging.
> Dockerfile: switch base image to distroless

- golink.go
When resolving links from an offline backup, this creates extra noise.
Updates tailscale/corp#22700
> print restored log statement only with verbose enabled

- Dockerfile
Without the git CLI, `go build` will not produce the embedded VCS metadata that's used to report the commit hash in node version string. This fixes the `1.72.1-ERR-BuildInfo` version string reported to Tailscale.
Fixes #140
> Dockerfile: install git to populate node version string

- golink.go
- golink_test.go
- tmpl/help.html
> add TrimPrefix, ToUpper, and ToLower template funcs

- golink.go
> Use default hostname in UI when in dev mode

- golink.go
By default, the directory chosen by tsnet is based on the name of the binary.
Allow the operator to set it explicitly, to avoid confusing deployments.
Signed-off-by: M. J. Fromberger <fromberger@tailscale.com>
> golink: add a --config-dir flag to override the default

- golink.go
- golink_test.go
It's not uncommon for auto-linkers or simple copy/paste errors to accidentally include trailing punctuation in a golink. When resolving links, if the initial link was not found, then try again with common punctuation (that is invalid in link names anyway) removed.
Fixes #148
> golink: strip trailing punctuation when resolving links

- flake.lock
- flake.nix
Closes #153
Things done:
- use flake-parts instead of flake-utils
- fix wrong version info by setting ldflags `"-X tailscale.com/version.longStamp=${tsVersion}"` and `"-X tailscale.com/version.shortStamp=${tsVersion}"`, where `tsVersion` is matched from `go.mod` using regex
- originally, `services.golink.package` is set to `pkgs.golink` by default (which is fine), however, the module does not apply the defined overlay, causing the module to use [the outdated golink from nixpkgs](https://search.nixos.org/packages?channel=unstable&show=golink&from=0&size=50&sort=relevance&type=packages&query=golink)
- update the dev shell go from 1.21 to 1.23
> flake.nix: refactor and correctly propagate tailscale version when deploying with nix

- golink.go
- golink_test.go
Preserve query parameters when redirecting from HTTP to HTTPS where previously they were omitted.
Fixes https://github.com/tailscale/golink/issues/163
> golink: preserve query during HTTP -> HTTPS redirects

- golink.go
- golink_test.go
- static/base.css
- tailwind.config.js
- tmpl/home.html
Right now, running in read-only mode displays a banner stating that links can be resolved but not created or updated, as well as actively blocking requests to modify links.
Update #118
Updates tailscale/corp#18849
> add support for running in read-only mode

- flake.nix
Since systemd service handles optional tailscaleAuthKeyFile, allow for optional declaration in the module. Tested and works with manual auth via admin console.
> Allow null tailscaleAuthKeyFile

- flake.lock
- flake.nix
The features used from flake-parts can be trivially replicated with the Nixpkgs lib itself
Most of the changes are to indentation, it's easier to review by disabling whitespace changes from the GitHub diff UI.
> refactor(nix): drop flake-parts dependency

- db.go
- flake.nix
- golink.go
- golink_test.go
This is really bare bones, but at least lets us get the stats data out. This also made it clear to me how brittle some of our tests are because of how much global state we have in the top-level golink package. We should probably move all of that into a server type or something similar before too long.
Updates #168
> add /.export-stats endpoint to dump stats table

- go.mod
- golink.go
- golink_test.go
Deprecate the use of xsrftokens entirely and replace them with requiring clients to send [Sec-Fetch-Site](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Sec-Fetch-Site) fetch metadata request headers that clarify the relationship between the initating and requested origin.
Add tests for `Sec-Golink` header behavior which continues to be permitted as a substitute for the new CSRF protection as was for the previous one.
Fixes #160 
Fixes #156 
Fixes #130
> golink: replace xsrftoken with Sec-Fetch-Site validation

- flake.nix
- tmpl/delete.html
- tmpl/detail.html
- tmpl/home.html
As of #177, we are now using Sec-Fetch-Site instead of xsrf tokens.
Updates #178
> remove XSRF input from templates

- .github/workflows/nix.yml
This patch uses Determinate Nix 3.3's feature of being able to automatically fix invalid Nix hashes in CI. I recently made this change in our fork of golinks, and thought I'd upstream it. 
It means PRs like https://github.com/tailscale/golink/pull/174 won't need manually pushing fixups too. They'll still need to be closed/reopened for GHA to run tests, though. See this PR on our fork for the same issue: https://github.com/DeterminateSystems/golink/pull/21
More context: https://determinate.systems/posts/changelog-determinate-nix-331/#automatic-hash-mismatches-fixes-in-github-actions
> Automatically fix flake.nix hashes from dependabot PRs

- golink.go
- golink_test.go
- tmpl/detail.html
- tmpl/help.html
Prior to #177, our XSRF tokens were bound to link IDs, with a special `.new` value used for newly created links. So if a user tried to create a link that already existed, the XSRF check would fail. After #177, this now silently allows the user to overwrite the existing link without any indication that this happened.
This change adds a hidden `update` param to the details edit form that must be present when updating an existing link.
Updates #177
> disallow accidental updates to existing links

- flake.nix
`pkgs.system` was deprecated over [4 years ago](https://github.com/NixOS/nixpkgs/commit/4246d6ce21d2d8d33e2d30f42b3d9d446c5dc143), the correct way to do this now is `pkgs.stdenv.hostPlatform.system`.
Fixes build on configs that set `nixpkgs.config.allowAliases = false`.
> refactor(nix): remove deprecated alias

- flake.nix
- go.mod
- golink.go
- golink_test.go
- tmpl/delete.html
- tmpl/detail.html
- tmpl/help.html
- tmpl/home.html
Unfortunately Sec-Fetch-Site headers are not sent over plaintext HTTP
making this unsuitable for non-TLS deployments.
Reverts c89d35095a4884eb84f7652b3376cf789592715f
Reverts 7646755c2e049abfeb65015115964c0bd3b2c887
Reverts a1ce1eb2b611877a42ae612e031c45b660543c51
Updates #160
Updates #156
Updates #130
> golink: revert Sec-Fetch-Site xsrftoken replacement

- README.md
Add an example `docker-compose.yml` for people to reference.
> Add docker compose instructions
